# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mariana Henriques
title: People & Culture enthusiast. An advocate of human-centric workplaces.
email: mmhenriques12@gmail.com
# email_title: Email (Email title override)
phone: +351 963 244 908
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mmhenriques12
linkedin_username: marianam-henriques

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/1610363054642.jpg
about_content: | # this will include new lines to allow paragraphs
  My journey so far has been about discovering how I can positively impact peoples' lives both in- and outside work. I am a big enthusiast of the techðŸŒ and passionate about crafting more transparent, agile and more human-centric workplaces always with smart and awesome people by my side â¤ï¸ Currently learning and doing this at [Valispace](https://www.valispace.com/). Otherwise you can find me doing cool stuff like:
  
    - Taking long walks (or simply cuddling) with my dog ðŸ¶ 
    - Roller skating ðŸ›¼
    - Tapestry in weaving for wall decor or ceramics ðŸŽ¨

content:
  - title: Work Experience
    layout: list
    content:
      - layout: right
        title: Valispace
        sub_title: Head of People Operations
        caption: May 2021 - present
        link: https://www.valispace.com/
        quote: >
          The GitHub for hardware engineering. 
        description: | # this will include new lines to allow paragraphs
         Currently helping to build an agile, modern and human People department to guide Valispace's growth ðŸš€ Besides hiring and onboarding, I'm developing and implementing people-driven strategies and programs that help everyone feel supported and enabled to do their best work. 
     

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
